### ISSUE TITLE
Options Inspector

### ISSUE THREAD

**Issue by szepeviktor** [charlestang/env#1]
@charlestang Dear Charles!

I've happend to write a plugin called :smile: https://github.com/szepeviktor/option-inspector
And then seen [your WP plugin](https://wordpress.org/plugins/options-inspector/) with the same name.

Could you add me as an admin to your plugin. I would then upload my plugin in place of yours.
My WP name is szepe.viktor.

Thank you very much!

**Comment by charlestang** [comment]
OK

Charles

--------

Success is not final, failure is not fatal: it is the courage to continue
that counts.
--  Winston Churchill

**Comment by szepeviktor** [comment]
Thank you very much. 
I'll upload my plugin when it is enhanced to provide all features of yours.

All the best wishes to you!

**Comment by szepeviktor** [comment]
Edit and search implemented.
https://github.com/szepeviktor/option-inspector
If you wish you can take a look at it.
